### ISSUE TITLE
Can we name the downloaded videos by session Id?

### ISSUE THREAD

**Issue by tulasiramgulla** [aimmac23/selenium-video-node#20] opened 2015-10-20 06:35 UTC
This is not an issue but a question/suggestion.We are finding the videos are being generated with some random numbers. Is there a rational behind naming these videos?. We think it'd be better if they are named with session id or combination of session Id and Node IP so that we can attach them to our test reports(e.g. ReportNG). as of now, we have no idea how to make use of them except keeping them on a central server or local disk.

**Comment by aimmac23** [comment] 2015-10-21 23:19
Hi tulasiramgulla,

Thanks for the feedback - its always good to hear how other people are using this project :)

> We are finding the videos are being generated with some random numbers. Is there a rational behind naming these videos?

The nodes store the videos with a temporary file name because the recording technically starts before the session has been fully created (the node assigns the official session IDs, but it hasn't been properly contacted yet to assign one).

>  We think it'd be better if they are named with session id or combination of session Id and Node IP so that we can attach them to our test reports(e.g. ReportNG)

Currently they are available using the session ID if you ask the Hub - it copies the video from the node after the selenium session has been properly closed, and makes it available for download using the sessionId, like so:

    http://<Hub URL>:4444/grid/admin/HubVideoDownloadServlet/?sessionId=38d9cb20-f3d7-40d5-8e08-6f31b2ed1506

> as of now, we have no idea how to make use of them except keeping them on a central server or local disk.

At work I was involved in writing a webapp to generate real-time selenium test progress reports, so unfortunately what I know is not directly transferrable to other people's use-cases.

From a bit of Googling, I found this answer (for attaching screenshots):

http://stackoverflow.com/questions/8939337/how-can-i-include-a-failure-screenshot-to-the-testng-report

I assume that you could try something like:

Reporter.log("<a href="  http://<Hub URL>:4444/grid/admin/HubVideoDownloadServlet/?sessionId=38d9cb20-f3d7-40d5-8e08-6f31b2ed1506">Test Video </a>

Or emit some HTML 5 video tags directly, I guess. Let me know how it goes.

Thanks,

Alasdair Macmillan

**Comment by aimmac23** [comment] 2015-10-21 23:21
Looks like the above didn't end well with Markdown - let's try again:

    Reporter.log("<a href="http://<Hub URL>:4444/grid/admin/HubVideoDownloadServlet/?sessionId=38d9cb20-f3d7-40d5-8e08-6f31b2ed1506">Video link</a>")

Or emit HTML 5 video tags directly. Let me know how it goes.

Thanks,

Alasdair Macmillan

**Comment by aimmac23** [comment] 2017-01-07 12:02
I assume the problem is resolved, so closing issue. Re-open it again if the above hasn't solved your problem.

Thanks,

Alasdair

**Closed by aimmac23** 2017-01-07 12:02 UTC
