### ISSUE TITLE
Video proxy deleting sessions

### ISSUE THREAD

**Issue by gerelasumit** [aimmac23/selenium-video-node#21] opened 2015-10-21 22:35 UTC
Hi Alasdair, I have been using your video-node plug in and its awesome! Thanks!
However, I'm facing one issue which is basically that VideoProxy is not able to start the recording. 
Below are the configurations I have for all the components:

1. Selenium Hub:
I start this using: java -Dvideo.storage="com.aimmac23.hub.videostorage.LocalFileVideoStore" \
  -Dvideo.path=/opt/video-recordings \
  -cp /opt/selenium-video.jar:/opt/selenium-server.jar org.openqa.grid.selenium.GridLauncher \
  -servlets com.aimmac23.hub.servlet.HubVideoDownloadServlet \
  -role hub
Hub Configuration is: {
  "browserTimeout": 120000,
  "newSessionWaitTimeout": 120000,
  "timeout": 60000
}

2. Selenium Nodes
Running jars with: xvfb-run -a -s "-screen 0 1280x1024x24 -wr" \
  java -cp /opt/selenium-video.jar:/opt/selenium-server.jar org.openqa.grid.selenium.GridLauncher \
  -servlets com.aimmac23.node.servlet.VideoRecordingControlServlet \
  -proxy com.aimmac23.hub.proxy.VideoProxy \
  -role wd \
  -nodeConfig /root/nodeconfig.json

nodeconfig.json (For selenium nodes):
{
  "capabilities": [
    {
      "browserName": "firefox",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "configuration":
  {
    "browserTimeout": 120000,
    "maxSession": 1,
    "host": ip,
    "hubHost": "some-ip",
    "timeout": 60000
  }
}
. Now when I run many of my test cases the hub logs as follows:
22:24:18.512 ERROR - Recording not started for dd0ab509-6a2d-4ff7-aee7-5c83176a511a on node http://10.244.6.73:5555 - cannot register session as stopping.
22:24:18.591 ERROR - Recording not started for dd0ab509-6a2d-4ff7-aee7-5c83176a511a on node http://10.244.6.73:5555 and session being deleted - this could be a bug in the code.
22:24:18.686 ERROR - Recording not started for 4ff38be4-6ed7-4f04-aecd-e31e8798a664 on node http://10.244.6.72:5555 - cannot register session as stopping.
22:24:18.817 ERROR - Recording not started for 4ff38be4-6ed7-4f04-aecd-e31e8798a664 on node http://10.244.6.72:5555 and session being deleted - this could be a bug in the code.
22:24:19.002 ERROR - Recording not started for 19b5934d-3b2b-465e-b876-06d48c2a1523 on node http://10.244.10.54:5555 - cannot register session as stopping.
22:24:19.135 ERROR - Recording not started for 19b5934d-3b2b-465e-b876-06d48c2a1523 on node http://10.244.10.54:5555 and session being deleted - this could be a bug in the code.
22:24:19.554 ERROR - Recording not started for 3cfaa538-e201-4b00-9606-9880b74503f4 on node http://10.244.10.55:5555 - cannot register session as stopping.
22:24:19.683 ERROR - Recording not started for 3cfaa538-e201-4b00-9606-9880b74503f4 on node http://10.244.10.55:5555 and session being deleted - this could be a bug in the code.
22:24:20.491 INFO - Selenium session closed for 0b45435d-d108-4222-9507-bf1ecd543043 on node http://10.244.4.70:5555 - stopping recording.
22:24:20.573 ERROR - Recording not started for a2a93fcb-147d-431e-9243-7b2717d45587 on node http://10.244.0.72:5555 - cannot register session as stopping.
22:24:20.703 ERROR - Recording not started for a2a93fcb-147d-431e-9243-7b2717d45587 on node http://10.244.0.72:5555 and session being deleted - this could be a bug in the code.
22:24:21.019 INFO - Successfully written video file for session to: /opt/video-recordings/0b45435d-d108-4222-9507-bf1ecd543043.webm
22:24:26.087 ERROR - Recording not started for 5e940fb3-f9b4-44d5-86a1-038e3df7a965 on node http://10.244.10.57:5555 - cannot register session as stopping.
22:24:26.217 ERROR - Recording not started for 5e940fb3-f9b4-44d5-86a1-038e3df7a965 on node http://10.244.10.57:5555 and session being deleted - this could be a bug in the code.
22:24:26.482 ERROR - Recording not started for ecccefde-0c68-412e-854a-6add3bdf1455 on node http://10.244.8.67:5555 - cannot register session as stopping.
22:24:26.616 ERROR - Recording not started for ecccefde-0c68-412e-854a-6add3bdf1455 on node http://10.244.8.67:5555 and session being deleted - this could be a bug in the code.
22:24:39.208 ERROR - Recording not started for 03fc7749-f8e4-43d5-8b59-e6fdb9e2e5ce on node http://10.244.0.70:5555 - cannot register session as stopping.
22:24:39.285 ERROR - Recording not started for 03fc7749-f8e4-43d5-8b59-e6fdb9e2e5ce on node http://10.244.0.70:5555 and session being deleted - this could be a bug in the code.
22:26:08.795 INFO - File not found, or is not readable for sessionId: 9f944111-ef4a-4fe8-a186-d0a6611c8046
22:26:08.795 INFO - Received request for video that was not found. Requested sessionId: 9f944111-ef4a-4fe8-a186-d0a6611c8046
.........

Is this something related to the my nodeconfig.json or bug in the plugin?

I would really appreciate your help.
Let me know if you need any more information.

-Sumit

**Comment by aimmac23** [comment] 2015-10-21 23:41
Hi gerelasumit.

It sounds like it could be a bug in the plugin. I'm kind of aware that if the hub gets terminated and restarted while the node was recording a video, then the hub doesn't manage to get the node back into a known state.

On the other hand, I'm not seeing the logging lines where the Hub tries to start a new recording - either the log provided has omitted those lines, or someone is repeatedly trying to delete dead sessions.

I would suggest trying to restart both the Hub and the nodes, to see if its issue #5 - if it is, I should finish the fix for that. If that doesn't work, we can try to look a bit deeper into the problem.

Another thing you could check is whether the IP address for your node matches the "host" JSON variable - but if it doesn't, I would expect your Selenium tests to fail anyway.

Thanks,

Alasdair Macmillan

**Comment by gerelasumit** [comment] 2015-10-22 00:04
Thanks for your reply. Yes I did omit the logs. Below are more detailed ones:
23:00:56.903 INFO - Successfully written video file for session to: /opt/video-recordings/905e3ea1-f016-4a7a-a7a2-bb5e4da26833.webm
23:00:56.950 ERROR - Recording not started for 284df94e-e94f-409d-b74e-dfd3d56ad859 on node http://10.244.1.67:5555 - cannot register session as stopping.
23:00:57.079 ERROR - Recording not started for 284df94e-e94f-409d-b74e-dfd3d56ad859 on node http://10.244.1.67:5555 and session being deleted - this could be a bug in the code.
23:00:57.136 INFO - Successfully written video file for session to: /opt/video-recordings/f5594ec7-f877-4bd8-9d8e-41f1c1bc353f.webm
23:00:57.193 ERROR - Recording not started for 9f4268cd-ab26-4073-92f4-40f2a7b49647 on node http://10.244.1.65:5555 - cannot register session as stopping.
23:00:57.223 INFO - Successfully written video file for session to: /opt/video-recordings/3e6dd9a9-1ab3-4e58-8155-c83f7a7afcf2.webm
23:00:57.275 ERROR - Recording not started for 9f4268cd-ab26-4073-92f4-40f2a7b49647 on node http://10.244.1.65:5555 and session being deleted - this could be a bug in the code.
23:00:57.579 ERROR - Recording not started for ebca91ee-54a5-4544-a901-1e48758545dd on node http://10.244.10.55:5555 - cannot register session as stopping.
23:00:57.660 ERROR - Recording not started for ebca91ee-54a5-4544-a901-1e48758545dd on node http://10.244.10.55:5555 and session being deleted - this could be a bug in the code.
23:00:58.122 INFO - Selenium session closed for 7e76e4ad-a9ed-4596-ab22-2d64724d9a33 on node http://10.244.5.67:5555 - stopping recording.
23:00:58.439 ERROR - Recording not started for 520c8264-81d2-42e1-a84b-53114c7d022a on node http://10.244.8.67:5555 - cannot register session as stopping.
23:00:58.567 ERROR - Recording not started for 520c8264-81d2-42e1-a84b-53114c7d022a on node http://10.244.8.67:5555 and session being deleted - this could be a bug in the code.
23:00:58.686 INFO - Successfully written video file for session to: /opt/video-recordings/7e76e4ad-a9ed-4596-ab22-2d64724d9a33.webm
23:00:59.171 ERROR - Recording not started for e513e42e-46eb-4c09-a947-3a27dc1452d6 on node http://10.244.6.74:5555 - cannot register session as stopping.
23:00:59.302 ERROR - Recording not started for e513e42e-46eb-4c09-a947-3a27dc1452d6 on node http://10.244.6.74:5555 and session being deleted - this could be a bug in the code.
23:01:00.439 ERROR - Recording not started for 3011a2cb-b4d2-404d-b306-fbe53a9be741 on node http://10.244.10.56:5555 - cannot register session as stopping.
23:01:00.576 ERROR - Recording not started for 3011a2cb-b4d2-404d-b306-fbe53a9be741 on node http://10.244.10.56:5555 and session being deleted - this could be a bug in the code.
23:01:01.686 INFO - Selenium session closed for e58ca43a-ab04-452f-af0e-385c2db765d2 on node http://10.244.11.61:5555 - stopping recording.
23:01:02.243 INFO - Successfully written video file for session to: /opt/video-recordings/e58ca43a-ab04-452f-af0e-385c2db765d2.webm
23:01:06.355 INFO - Selenium session closed for 3f5cdd39-f760-482e-84d5-6ae0695312ef on node http://10.244.7.68:5555 - stopping recording.
23:01:06.897 INFO - Successfully written video file for session to: /opt/video-recordings/3f5cdd39-f760-482e-84d5-6ae0695312ef.webm
23:01:07.693 INFO - Selenium session closed for 6e358770-d7e8-4e1e-865c-f5ca42d187e9 on node http://10.244.5.68:5555 - stopping recording.
23:01:08.255 INFO - Successfully written video file for session to: /opt/video-recordings/6e358770-d7e8-4e1e-865c-f5ca42d187e9.webm
23:01:31.104 INFO - Got a request to create a new session: Capabilities [{browserName=firefox, version=, platform=ANY}]
23:01:31.104 INFO - Available nodes: [http://10.244.1.66:5555, http://10.244.6.73:5555, http://10.244.1.67:5555, http://10.244.6.72:5555, http://10.244.8.68:5555, http://10.244.6.74:5555, http://10.244.6.71:5555, http://10.244.1.65:5555, http://10.244.6.70:5555, http://10.244.8.67:5555, http://10.244.5.70:5555, http://10.244.5.68:5555, http://10.244.5.69:5555, http://10.244.5.67:5555, http://10.244.5.66:5555, http://10.244.10.56:5555, http://10.244.9.73:5555, http://10.244.9.74:5555, http://10.244.9.72:5555, http://10.244.10.55:5555, http://10.244.10.54:5555, http://10.244.10.57:5555, http://10.244.10.59:5555, http://10.244.10.53:5555, http://10.244.11.60:5555, http://10.244.11.59:5555, http://10.244.11.61:5555, http://10.244.10.58:5555, http://10.244.4.70:5555, http://10.244.4.71:5555, http://10.244.4.73:5555, http://10.244.4.72:5555, http://10.244.0.73:5555, http://10.244.0.70:5555, http://10.244.0.75:5555, http://10.244.0.72:5555, http://10.244.0.77:5555, http://10.244.0.76:5555, http://10.244.0.71:5555, http://10.244.0.74:5555, http://10.244.7.68:5555, http://10.244.7.67:5555, http://10.244.7.69:5555, http://10.244.7.70:5555, http://10.244.3.78:5555, http://10.244.3.79:5555, http://10.244.2.77:5555, http://10.244.2.78:5555, http://10.244.2.76:5555, http://10.244.3.80:5555]
23:01:31.104 INFO - Trying to create a new session on node http://10.244.1.66:5555
23:01:31.104 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, browserName=firefox, maxInstances=1, platform=LINUX}
23:01:31.106 WARN - Could not start video reporting: Internal server error while trying to start recording: Video recording currently in progress, cannot record again
23:01:57.403 ERROR - Recording not started for 2dfc6b3d-5e3c-4368-a15f-9db01faf1e1b on node http://10.244.1.66:5555 - cannot register session as stopping.
23:01:57.478 ERROR - Recording not started for 2dfc6b3d-5e3c-4368-a15f-9db01faf1e1b on node http://10.244.1.66:5555 and session being deleted - this could be a bug in the code.
23:02:03.399 INFO - File not found, or is not readable for sessionId: 2dfc6b3d-5e3c-4368-a15f-9db01faf1e1b
23:02:03.399 INFO - Received request for video that was not found. Requested sessionId: 2dfc6b3d-5e3c-4368-a15f-9db01faf1e1b
23:10:19.654 INFO - File not found, or is not readable for sessionId: 2dfc6b3d-5e3c-4368-a15f-9db01faf1e1b
23:10:19.654 INFO - Received request for video that was not found. Requested sessionId: 2dfc6b3d-5e3c-4368-a15f-9db01faf1e1b

I would try restarting the hub and nodes sometime later tonight and check if the issue still persist, I'm running everything inside docker so updated the hub docker image on the fly while the connected nodes were still executing the test and hub just restarted in the middle. I believe hub is in weird state! Let me restart the hub later tonight and I will update you about it, hopefully it behaves normally :)

Thanks!

**Comment by gerelasumit** [comment] 2015-10-22 21:55
Hey, The issue seems to be gone and videos are being persisted locally after re-starting hub and the nodes.
Thanks!

**Comment by aimmac23** [comment] 2015-10-23 12:39
Good to hear - in which case I'll close the issue as a duplicate of issue #5 

Thanks,

Alasdair

**Closed by aimmac23** 2015-10-23 12:39 UTC
