### ISSUE TITLE
Unable to start selenium test by given examples: ExampleSeleniumTests.java and AbstractVideoSeleniumTest.java

### ISSUE THREAD

**Issue by mosadchiy** [aimmac23/selenium-video-node#57] opened 2018-08-15 09:37 UTC
After successfully running grid hub:
java -cp selenium-video-node-2.8.jar;selenium-server-standalone-3.13.0.jar org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.hub.servlet.HubVideoDownloadServlet -role hub
And grid node:
java -cp selenium-video-node-2.8.jar;selenium-server-standalone-3.13.0.jar org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.node.servlet.VideoRecordingControlServlet -proxy com.aimmac23.hub.proxy.VideoProxy -role wd

I was not able to run selenium test from given example:
return new RemoteWebDriver(hubUrl, new ChromeOptions());
This line throws the following exception:
org.openqa.selenium.SessionNotCreatedException: Unable to create new service: ChromeDriverService
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'WWL-20171109-I7', ip: '192.168.113.124', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.2'
Driver info: driver.version: unknown
Command duration or timeout: 261 milliseconds

Almost the same error for Firefox (gecko):
return new RemoteWebDriver(hubUrl, new FirefoxOptions().setLegacy(false));
org.openqa.selenium.SessionNotCreatedException: Unable to create new service: GeckoDriverService
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'WWL-20171109-I7', ip: '192.168.113.124', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.2'
Driver info: driver.version: unknown
Command duration or timeout: 158 milliseconds

Could you please assist me what I do wrong?

**Comment by aimmac23** [comment] 2018-08-15 09:53
Chrome support doesn't work out of the box for Selenium - you have to also have a separate binary file:

https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver

The binary also only supports a range of Chrome versions - check that you have the correct Chrome version for the binary.

The Selenium node should have better error logging than the Selenium client.

Closing, as the issue is not part of this project.

**Closed by aimmac23** 2018-08-15 09:53 UTC
